# Generated by Django 2.2.3 on 2019-07-30 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('freeboard', '0002_auto_20190730_1906'),
    ]

    operations = [
        migrations.RenameField(
            model_name='star',
            old_name='description',
            new_name='body',
        ),
    ]
